export interface SeedQuestion {
  texto: string;
  categoria?: string;
  status?: 'aprovada' | 'pendente' | 'rejeitada';
}

export const INITIAL_QUESTIONS: SeedQuestion[] = [
  // Boteco & Comida
  { texto: 'Qual é o melhor petisco de boteco de todos os tempos?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual é a melhor pizza de um sabor tradicional?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual salgado de lanchonete de rua é imbatível?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual ingrediente não pode faltar no cachorro-quente perfeito?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor sabor de sorvete para um dia quente?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual é a fruta mais gostosa de comer bem gelada?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual prato de almoço de domingo na casa da avó é o melhor?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Se você pudesse comer apenas uma sobremesa pelo resto da vida, qual seria?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual bebida gelada combina perfeitamente com um churrasco?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o pastel de feira mais gostoso?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual comida congelada salva o jantar quando dá preguiça de cozinhar?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual é o melhor recheio para uma tapioca quente?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o doce de aniversário infantil mais disputado na mesa?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Se tiver que escolher só uma massa, qual a melhor de todas?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual é a melhor fruta para fazer suco natural?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor aperitivo para comer vendo um filme no sofá?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual é o melhor sabor de pastel doce?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual tempero ou molho melhora qualquer comida sem graça?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual é a comida de café da manhã que dá mais felicidade?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor recheio de coxinha?', categoria: 'Boteco & Comida', status: 'aprovada' },

  // Cotidiano & Perrengues
  { texto: 'Qual é a pior tarefa doméstica de se fazer no fim de semana?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual objeto da casa tem uma facilidade incrível de sumir sem explicação?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual é o dia da semana mais chato?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual é a desculpa mais clássica para chegar atrasado no compromisso?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual é a primeira coisa que você faz assim que acorda?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual é o barulho mais irritante que pode acordar alguém de manhã?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o melhor lugar da casa para relaxar e não fazer nada?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o perrengue mais comum quando se pega transporte público lotado?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a mensagem que todo mundo odeia receber no WhatsApp?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'O que não pode faltar na bolsa ou mochila ao sair de casa?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o aplicativo de celular que você mais usa por dia?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a coisa mais constrangedora que pode acontecer num elevador cheio?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual é o melhor momento do dia de trabalho ou estudo?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Se o celular cair no chão, qual a primeira coisa que passa pela cabeça?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual é o hábito mais estranho que muitas pessoas escondem?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'O que você faz quando vê alguém conhecido na rua mas não quer cumprimentar?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o item mais inútil que todo mundo tem guardado numa gaveta?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o lugar onde a bateria do celular sempre decide acabar?', categoria: 'Cotidiano', status: 'aprovada' },

  // Cultura Pop & Entretenimento
  { texto: 'Qual é o filme mais marcante de animação da infância?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual super-herói venceria em uma batalha todos contra todos?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual gênero de filme é o melhor para assistir com amigos no cinema?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual o vilão mais inesquecível da história do cinema ou TV?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual desenho animado nostálgico deveria ganhar novas temporadas?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual artista ou banda nacional todo brasileiro sabe cantar pelo menos uma música?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual o meme clássico da internet brasileira que nunca perde a graça?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual jogo de tabuleiro acaba com qualquer amizade?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual reality show dá mais vontade de comentar nas redes sociais?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual saga de filmes é a melhor para fazer uma maratona no fim de semana?', categoria: 'Cultura Pop', status: 'aprovada' },

  // Cachorros & Mundo Animal
  { texto: 'Qual é a raça de cachorro mais simpática e carismática?', categoria: 'Mundo Canino', status: 'aprovada' },
  { texto: 'Qual o nome mais comum e clássico para um cachorro no Brasil?', categoria: 'Mundo Canino', status: 'aprovada' },
  { texto: 'O que o seu cachorro provavelmente pensa quando você sai de casa?', categoria: 'Mundo Canino', status: 'aprovada' },
  { texto: 'Qual o petisco que deixa qualquer cão louco de alegria?', categoria: 'Mundo Canino', status: 'aprovada' },
  { texto: 'Se os cães tivessem uma profissão humana, qual seria a mais combinando?', categoria: 'Mundo Canino', status: 'aprovada' },
  { texto: 'Qual o lugar onde o cachorro mais gosta de receber carinho?', categoria: 'Mundo Canino', status: 'aprovada' },
  { texto: 'Qual é a brincadeira favorita de 10 em cada 10 cães?', categoria: 'Mundo Canino', status: 'aprovada' },
  { texto: 'Qual animal selvagem daria o melhor mascote se não fosse perigoso?', categoria: 'Mundo Canino', status: 'aprovada' },
  { texto: 'Qual o som ou palavra que faz o cachorro levantar as orelhas na hora?', categoria: 'Mundo Canino', status: 'aprovada' },

  // Superpoderes & Situacionais
  { texto: 'Se você pudesse ter apenas um superpoder, qual escolheria?', categoria: 'Hipotéticos', status: 'aprovada' },
  { texto: 'Se ganhasse na loteria hoje, qual seria a primeira compra extravagante?', categoria: 'Hipotéticos', status: 'aprovada' },
  { texto: 'Se pudesse viajar no tempo para qualquer época, para onde iria?', categoria: 'Hipotéticos', status: 'aprovada' },
  { texto: 'Se você ficasse preso em uma ilha deserta, qual objeto levaria?', categoria: 'Hipotéticos', status: 'aprovada' },
  { texto: 'Se pudesse jantar com qualquer pessoa viva ou morta, quem seria?', categoria: 'Hipotéticos', status: 'aprovada' },
  { texto: 'Se pudesse dominar instantaneamente qualquer instrumento musical, qual seria?', categoria: 'Hipotéticos', status: 'aprovada' },
  { texto: 'Se você virasse invisível por um dia, qual a primeira coisa que faria?', categoria: 'Hipotéticos', status: 'aprovada' },
  { texto: 'Se você pudesse aprender qualquer idioma instantaneamente, qual seria?', categoria: 'Hipotéticos', status: 'aprovada' },

  // Infância & Nostalgia
  { texto: 'Qual a melhor brincadeira de infância da rua?', categoria: 'Nostalgia', status: 'aprovada' },
  { texto: 'Qual doce baratinho da infância dá mais saudade?', categoria: 'Nostalgia', status: 'aprovada' },
  { texto: 'Qual o brinquedo que todo mundo queria ter quando era criança?', categoria: 'Nostalgia', status: 'aprovada' },
  { texto: 'Qual frase que os pais falavam que hoje em dia faz total sentido?', categoria: 'Nostalgia', status: 'aprovada' },
  { texto: 'Qual era a matéria mais legal na escola primaria?', categoria: 'Nostalgia', status: 'aprovada' },
  { texto: 'Qual programa de TV da infância marcou suas manhãs?', categoria: 'Nostalgia', status: 'aprovada' },

  // Estilo de Vida & Viagens
  { texto: 'Qual o destino de viagem dos sonhos para passar férias inesquecíveis?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Praia ou Montanha: qual é o refúgio perfeito no final de semana?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual a estação do ano mais gostosa de viver?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual presente genérico de aniversário todo mundo já deu ou recebeu?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual a atividade perfeita para um domingo à tarde chuvoso?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual calçado é o campeão absoluto de conforto?', categoria: 'Estilo de Vida', status: 'aprovada' },

  // E mais 140 perguntas super variadas para fechar 200+
  { texto: 'Qual é o maior medo bobo que muitos adultos têm?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual comida fica ainda mais gostosa no dia seguinte?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual aplicativo de navegação você mais confia?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o melhor recheio de pastel de feira?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual esporte é mais emocionante de assistir na Olimpíada?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual a melhor invenção da humanidade para o conforto moderno?', categoria: 'Hipotéticos', status: 'aprovada' },
  { texto: 'Qual é o melhor recheio para um sanduíche natural?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a primeira coisa que você olha em um cardápio de restaurante?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a música que não pode faltar em uma festa de casamento?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual a melhor cor para um carro novo?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual é o pior barulho quando se está tentando dormir?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual tempero deixa o feijão com gosto de comida de mãe?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor sabor de refrigerante?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a fruta mais chata de descascar?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor horário para tomar um banho relaxante?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a coisa que mais faz a pessoa perder a paciência no trânsito?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o melhor complemento para comer com açaí?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual animal seria o mais engraçado se falasse português?', categoria: 'Mundo Canino', status: 'aprovada' },
  { texto: 'Qual o melhor sabor de empada?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual presente de amigo secreto é o mais sem erro?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual a melhor sobremesa de padaria?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual tipo de suco combina mais com almoço caseiro?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor acompanhamento para o churrasco além da carne?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual canal ou estilo de vídeo no YouTube você assiste sem ver o tempo passar?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual o item mais importante para levar na praia?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual a melhor hora de tomar café no dia?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o melhor biscoito ou bolacha de pacote?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o lugar do avião ou ônibus que todos preferem sentar?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual estilo de música serve para qualquer momento?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual o melhor recheio de crepe ou panqueca?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a primeira palavra que vem à mente quando se pensa em calor forte?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o objeto que sempre quebra na hora mais errada?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a comida mais gostosa em um dia frio de inverno?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor fruto do mar?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual é o melhor recheio de bolo de aniversário?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual animal da fazenda é o mais simpático?', categoria: 'Mundo Canino', status: 'aprovada' },
  { texto: 'Qual o hábito mais saudável que pouca gente consegue manter?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual o melhor sabor de pipoca no cinema?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o meme da internet que marcou uma época inteira?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual a peça de roupa favorita para ficar em casa descansando?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual a sobremesa de Páscoa mais esperada?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor sabor de suco de caixinha?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a frase mais dita antes de uma foto em grupo?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a melhor invenção para a cozinha?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a cor de camiseta mais versátil do guarda-roupa?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual o legume ou hortaliça que mais gente rejeita quando criança?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor lugar para passar o Ano Novo?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual o petisquinho de saquinho mais viciante?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a melhor lembrança de festa infantil de antigamente?', categoria: 'Nostalgia', status: 'aprovada' },
  { texto: 'Qual a primeira coisa a fazer quando cai a energia elétrica em casa?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o tipo de pão mais gostoso bem quentinho com manteiga?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o esporte mais legal de praticar com amigos no fim de semana?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual o objeto que você mais morre de medo de perder na rua?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a melhor calda para colocar no pudim de leite?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o animal marinho mais fascinante de todos?', categoria: 'Mundo Canino', status: 'aprovada' },
  { texto: 'Qual o aroma mais gostoso que existe no ar?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o melhor recheio para pastel frito na hora?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o jogo de celular mais viciante que já existiu?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual o lugar onde o Wi-Fi nunca funciona direito?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o melhor prato para fazer com arroz de ontem?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a primeira coisa a colocar na mala de viagem?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual o melhor corte de carne para churrasco?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a melhor música para cantar no karaokê sem vergonha?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual a guloseima favorita de cinema além da pipoca?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o hábito de limpeza mais satisfatório de fazer?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a fruta mais doce e saborosa do verão?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a maior vantagem de trabalhar em home office?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o brinquedo de parque de diversões mais assustador?', categoria: 'Nostalgia', status: 'aprovada' },
  { texto: 'Qual o sabor de esfiha mais pedido?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a maior desculpa para não ir à academia hoje?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a sobremesa tradicional de Natal que divide opiniões?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o objeto de infância que trazia felicidade imediata?', categoria: 'Nostalgia', status: 'aprovada' },
  { texto: 'Qual a primeira coisa que você pede quando chega na lanchonete?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o instrumento musical com o som mais bonito?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual o personagem de desenho animado mais engraçado?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual a melhor maneira de economizar tempo no dia a dia?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a comida de rua mais rápida e saborosa?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor sabor de mil-shake?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a sensação física mais gostosa do dia?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a flor ou planta mais bonita para ter no jardim?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual a melhor hora de dar um mergulho no mar?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual o alimento que não pode faltar no carrinho de feira?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a pergunta mais difícil que te fazem em entrevistas?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o melhor aplicativo para ouvir música?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual o item de papelaria mais gostoso de comprar novo?', categoria: 'Nostalgia', status: 'aprovada' },
  { texto: 'Qual o melhor recheio para torta salgada?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o prato de comida chinesa mais popular no Brasil?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a bebida mais refrescante num dia de calorão?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a melhor fruta para colocar na salada de frutas?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o vilão de filme que no fundo tinha um pouco de razão?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual o melhor acompanhamento para uma feijoada completa?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o acessório mais útil em um dia de chuva forte?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o tempero essencial no molho de tomate caseiro?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o esporte mais praticado nas praias brasileiras?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual o melhor jeito de preparar ovo de manhã?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a coisa que mais te faz rir em um vídeo na internet?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual a sobremesa gelada mais rápida de fazer em casa?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor lugar para ver o pôr do sol?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual o brinquedo que todo mundo jogava no recreio da escola?', categoria: 'Nostalgia', status: 'aprovada' },
  { texto: 'Qual o petisco perfeito para acompanhar uma conversa longa?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a palavra em português que é a mais bonita de falar?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a melhor invenção para não passar frio nos pés?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o personagem mais icônico da televisão brasileira?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual o melhor queijo para derreter em um lanche quentinho?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a primeira coisa a fazer quando o computador trava?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a sobremesa de fruta mais gostosa?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o momento de maior suspense em um filme de terror?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual o produto de beleza ou higiene indispensável diário?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o melhor sabor de picolé na praia?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o animal de estimação mais fácil de cuidar?', categoria: 'Mundo Canino', status: 'aprovada' },
  { texto: 'Qual o melhor prato típico de festa junina?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o som da natureza mais relaxante de se ouvir?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual a melhor fruta para fazer geleia caseira?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a peça de roupa que nunca sai de moda?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual a frase clássica de mãe quando a gente vacila?', categoria: 'Nostalgia', status: 'aprovada' },
  { texto: 'Qual o prato de massa mais reconfortante num dia triste?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor momento para escutar podcast ou rádio?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a invenção da tecnologia que mais revolucionou as relações?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual o lugar mais gostoso de tirarem uma soneca de 15 minutos?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o doce de colher mais viciante?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor presente para dar a um recém-nascido?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual o alimento que fica mais gostoso com canela em pó?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor destino brasileiro para quem ama natureza?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual o personagem de videogame mais lendário?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual a melhor comida para um piquenique no parque?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a maior invenção para evitar mosquitos e pernilongos?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a sobremesa de chocolate que ninguém consegue recusar?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o canal de TV fechada ou streaming com as melhores séries?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual o animal marinho mais simpático nos aquários?', categoria: 'Mundo Canino', status: 'aprovada' },
  { texto: 'Qual a melhor fruta para secar e comer como snack?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o hábito da manhã que muda a produtividade do dia?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual o item mais esquecido quando as pessoas vão acampar?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual a melhor música para dar energia no treino?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual o sabor de fondue favorito: Doce ou Salgado?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a melhor maneira de fazer amigos novos quando adulto?', categoria: 'Cotidiano', status: 'aprovada' },
  { texto: 'Qual a frase de filme que virou jargão na vida real?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual a comida rápida favorita de madrugada?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o melhor tempero para frango grelhado?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a lembrança de viagem mais comum de se comprar de presente?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual o melhor sabor de rosca de padaria?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o esporte olímpico mais curioso de assistir?', categoria: 'Cultura Pop', status: 'aprovada' },
  { texto: 'Qual a fruta perfeita para bater no liquidificador com leite?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual a melhor companhia para fazer uma viagem longa de carro?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual o aperitivo mais servido em festas de fim de ano?', categoria: 'Boteco & Comida', status: 'aprovada' },
  { texto: 'Qual o objeto decorativo mais simpático para a sala de estar?', categoria: 'Estilo de Vida', status: 'aprovada' },
  { texto: 'Qual a pergunta mais engraçada que uma criança já te fez?', categoria: 'Nostalgia', status: 'aprovada' },
  { texto: 'Qual a comida de boteco que mais sustenta?', categoria: 'Boteco & Comida', status: 'aprovada' }
];
