export const LIMITS = {
  MIN_PLAYERS: 4,
  MAX_PLAYERS: 20,

  ANSWER_MIN_LENGTH: 1,
  ANSWER_MAX_LENGTH: 40,

  TIMER_MIN_SECONDS: 30,
  TIMER_MAX_SECONDS: 120,
  TIMER_DEFAULT_SECONDS: 60,

  ROUNDS_MIN: 6,
  ROUNDS_MAX: 20,
  ROUNDS_DEFAULT: 10,

  TARGET_MIN: 12,
  TARGET_MAX: 40,
  TARGET_DEFAULT: 20,

  ROOM_CODE_LENGTH: 4,
  ROOM_EXPIRE_MS: 2 * 60 * 60 * 1000,

  JUDGE_TIMEOUT_MS: 6000,
  JUDGE_RETRIES: 0,

  ABSENT_ROUNDS_BEFORE_REMOVE: 2,

  POINTS_MATILHA: 2,
  POINTS_PERDIDOS: 1,
  POINTS_LOBO: 0,
} as const;

export const DEFAULT_SETTINGS = {
  mode: 'rounds' as const,
  totalRounds: LIMITS.ROUNDS_DEFAULT,
  targetScore: LIMITS.TARGET_DEFAULT,
  timeLimitSeconds: LIMITS.TIMER_DEFAULT_SECONDS,
};
